version: "3.8"
services:
  ui:
    image: get-out:dev
    restart: always
    container_name: get-out
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./app:/usr/get-out/app
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    container_name: db
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
